(function(){
'use strict';
const ADMIN_ID='admin', ADMIN_PASS='1234';
const LS_RECORDS='belle_house_tenko_v40_records', LS_DRIVERS='belle_house_tenko_v40_drivers', LS_ADMINS='belle_house_tenko_v40_admins';
const APP_VERSION='Ver.7.0';
let currentUser='', gpsData=null, selectedCommentRecordId=null;
let cloudStarted=false, cloudRetryCount=0, cloudLastError='';
const CHECK_ITEMS=[['alcDevice','アルコール検知器を使用した'],['alcNone','酒気帯びなし'],['healthGood','疾病・疲労・睡眠不足なし'],['sleepOk','睡眠不足なし'],['licenseOk','運転免許証を携帯・有効確認'],['dailyInspection','日常点検を実施'],['vehicleOk','車両に異常なし'],['tireOk','タイヤ・灯火・ブレーキ確認'],['cargoOk','積荷・荷崩れ防止確認'],['overloadOk','過積載なし'],['restOk','休憩・拘束時間に無理なし'],['instructionOk','運行上の注意事項を確認']];
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const nowText=()=>new Date().toLocaleString('ja-JP',{hour12:false});
const todayKey=()=>new Date().toLocaleDateString('ja-JP');
const isoDate=()=>new Date().toISOString().slice(0,10);
const monthKey=()=>new Date().toISOString().slice(0,7);
const getLocal=k=>JSON.parse(localStorage.getItem(k)||'[]');
const setLocal=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const getRecords=()=>getLocal(LS_RECORDS); const getDrivers=()=>getLocal(LS_DRIVERS); const getAdmins=()=>getLocal(LS_ADMINS);
function bind(id,ev,fn){const el=$(id); if(el) el.addEventListener(ev,fn)}
function init(){updateSyncStatus(); renderCheckList(); bindEvents(); startCloudSync(); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});}
function bindEvents(){
 bind('loginBtn','click',login); bind('gpsBtn','click',getGPS); bind('submitRollcallBtn','click',submitRollcall); bind('driverLogoutBtn','click',()=>location.reload()); bind('adminLogoutBtn','click',()=>location.reload());
 bind('exportCsvBtn','click',exportCSV); bind('printPdfBtn','click',()=>{showAdminTab('records');setTimeout(()=>window.print(),200)}); bind('backupBtn','click',backupData); bind('restoreBtn','click',()=>$('restoreInput')?.click()); bind('restoreInput','change',restoreData); bind('clearRecordsBtn','click',clearRecords);
 bind('addDriverBtn','click',addDriver); bind('addAdminBtn','click',addAdmin); bind('photoInput','change',previewPhoto); bind('removePhotoBtn','click',removePhoto);
 bind('recordsBody','click',handleRecordClick); bind('saveCommentBtn','click',saveAdminComment); bind('closeCommentBtn','click',closeCommentPanel); bind('driverNoticeList','click',handleNoticeClick);
 document.querySelectorAll('.admin-nav button[data-tab]').forEach(b=>b.onclick=()=>showAdminTab(b.dataset.tab));
 $('driversBody')?.addEventListener('click',e=>{if(e.target.dataset.deleteDriver!==undefined)deleteDriver(+e.target.dataset.deleteDriver)});
 $('adminsBody')?.addEventListener('click',e=>{if(e.target.dataset.deleteAdmin!==undefined)deleteAdmin(+e.target.dataset.deleteAdmin)});
}
function updateSyncStatus(){const b=$('syncStatus'); if(!b)return; const cloud=!!(window.BELLE_CLOUD&&window.BELLE_CLOUD.enabled); b.textContent=cloud?(navigator.onLine?'クラウド同期ON':'オフライン保存中'):'ローカル保存'; b.className='sync-badge '+(cloud?'cloud':'local');}
function sortByNewest(a){return [...(a||[])].sort((x,y)=>String(y.createdAt||y.time||y.id||'').localeCompare(String(x.createdAt||x.time||x.id||'')))}
function startCloudSync(){const c=window.BELLE_CLOUD; if(cloudStarted)return; if(!c||!c.enabled){if(cloudRetryCount<20){cloudRetryCount++;setTimeout(startCloudSync,500)} return} cloudStarted=true; updateSyncStatus(); if(c.onRecords)c.onRecords(r=>{setLocal(LS_RECORDS,sortByNewest(r));refreshCurrentViews()}); if(c.onDrivers)c.onDrivers(d=>{setLocal(LS_DRIVERS,sortByNewest(d));refreshCurrentViews()}); if(c.onAdmins)c.onAdmins(a=>{setLocal(LS_ADMINS,sortByNewest(a));refreshCurrentViews()}); uploadLocalDataToCloud();}
function refreshCurrentViews(){updateDashboard();renderDriverOptions();renderRecords();renderDrivers();renderAdmins();renderDriverNotices()}
async function uploadLocalDataToCloud(){const c=window.BELLE_CLOUD; if(!c||!c.enabled)return; try{for(const r of getRecords())if(r?.id&&c.saveRecord)await c.saveRecord(r); for(const d of getDrivers())if(d?.id&&c.saveDriver)await c.saveDriver(d); for(const a of getAdmins())if(a?.id&&c.saveAdmin)await c.saveAdmin(a)}catch(e){console.warn(e)}}
async function cloudSave(kind,data){const c=window.BELLE_CLOUD; if(!c||!c.enabled)return; try{if(kind==='record'&&c.saveRecord)await c.saveRecord(data); if(kind==='driver'&&c.saveDriver)await c.saveDriver(data); if(kind==='admin'&&c.saveAdmin)await c.saveAdmin(data)}catch(e){console.error(e);alert('クラウド保存に失敗しました。ローカルには保存されています。')}}
async function cloudDelete(kind,id){const c=window.BELLE_CLOUD; if(!c||!c.enabled)return; try{if(kind==='driver'&&c.deleteDriver)await c.deleteDriver(String(id)); if(kind==='admin'&&c.deleteAdmin)await c.deleteAdmin(String(id))}catch(e){console.error(e)}}
function renderCheckList(){const box=$('checkList'); if(!box)return; box.innerHTML=CHECK_ITEMS.map(([id,l])=>`<div class="check"><label><input type="checkbox" id="${id}">${l}</label></div>`).join('')}
function login(){const type=$('loginType').value, name=$('loginName').value.trim(), pass=$('loginPassword').value.trim(); if(!name||!pass){alert('名前とパスワードを入力してください');return} if(type==='admin'){const extra=getAdmins().some(a=>String(a.name).trim()===name&&String(a.pass).trim()===pass); if((name===ADMIN_ID&&pass===ADMIN_PASS)||extra){$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');showAdminTab('dashboard');return} alert('管理者IDまたはパスワードが違います');return} currentUser=name; $('currentDriver').textContent=`${name} さん`; const d=getDrivers().find(x=>x.name===name); if(d?.vehicle)$('vehicleNo').value=d.vehicle; $('loginView').classList.add('hidden');$('driverView').classList.remove('hidden'); renderDriverNotices();}
function getGPS(){if(!navigator.geolocation){alert('GPS非対応です');return} $('gpsText').value='取得中...'; navigator.geolocation.getCurrentPosition(p=>{gpsData={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,time:nowText()}; $('gpsText').value=`緯度:${gpsData.lat.toFixed(6)} 経度:${gpsData.lng.toFixed(6)} 精度:${Math.round(gpsData.accuracy)}m`;},()=>{gpsData=null;$('gpsText').value='取得失敗';alert('GPS取得に失敗しました。')},{enableHighAccuracy:true,timeout:10000,maximumAge:0})}
function previewPhoto(){const f=$('photoInput')?.files?.[0]; if(!f){$('photoPreview')?.classList.add('hidden');return} const r=new FileReader(); r.onload=()=>{$('photoPreview').src=r.result;$('photoPreview').classList.remove('hidden')}; r.readAsDataURL(f)}
function removePhoto(silent=false){if($('photoInput'))$('photoInput').value=''; if($('photoPreview')){$('photoPreview').src='';$('photoPreview').classList.add('hidden')} if(!silent)alert('添付写真を削除しました')}
function resizePhotoFile(file){return new Promise((resolve,reject)=>{if(!file){resolve('');return} if(!file.type.startsWith('image/')){alert('画像ファイルを選択してください');resolve('');return} const reader=new FileReader(); reader.onload=()=>{const img=new Image(); img.onload=()=>{const max=900, scale=Math.min(1,max/Math.max(img.width,img.height)); const canvas=document.createElement('canvas'); canvas.width=Math.round(img.width*scale); canvas.height=Math.round(img.height*scale); canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height); resolve(canvas.toDataURL('image/jpeg',0.72))}; img.onerror=()=>reject(new Error('写真の処理に失敗しました')); img.src=reader.result}; reader.onerror=()=>reject(new Error('写真の読み込みに失敗しました')); reader.readAsDataURL(file)})}
function detectCourse(){const t=(($('deliveryNote')?.value||'')+' '+($('remarks')?.value||'')); if(t.includes('Amazon'))return'Amazon'; if(t.includes('ヤマト'))return'ヤマト'; if(t.includes('佐川'))return'佐川'; if(t.includes('スポット'))return'スポット便'; return''}
async function submitRollcall(){const checks={}; CHECK_ITEMS.forEach(([id])=>checks[id]=!!$(id)?.checked); const allOk=CHECK_ITEMS.every(([id])=>checks[id]); if(!allOk&&!confirm('未チェック項目があります。要確認として送信しますか？'))return; try{const photo=await resizePhotoFile($('photoInput')?.files?.[0]); const rec={id:String(Date.now()),ok:allOk,time:nowText(),date:todayKey(),isoDate:isoDate(),month:monthKey(),driver:currentUser,name:currentUser,type:$('rollcallType').value,method:$('rollcallMethod').value,vehicleNo:$('vehicleNo').value.trim(),odometer:$('odometer').value.trim(),alcoholValue:$('alcoholValue').value.trim(),alcohol:$('alcoholValue').value.trim(),sleepHours:$('sleepHours').value.trim(),health:checks.healthGood?'良好':'要確認',instruction:$('instruction').value.trim(),deliveryNote:$('deliveryNote').value.trim(),course:detectCourse(),checks,gps:gpsData,photo:photo||'',remarks:$('remarks').value.trim(),adminComment:'',commentRead:true,createdAt:nowText()}; const arr=getRecords(); arr.unshift(rec); setLocal(LS_RECORDS,arr); await cloudSave('record',rec); alert(window.BELLE_CLOUD?.enabled?'点呼を送信しました（クラウド同期済み）':'点呼を保存しました（ローカル保存）'); removePhoto(true);}catch(e){alert(e.message||'送信に失敗しました')}}
function showAdminTab(tab){document.querySelectorAll('.admin-tab').forEach(e=>e.classList.add('hidden')); $(`${tab}Tab`)?.classList.remove('hidden'); if(tab==='dashboard')updateDashboard(); if(tab==='records'){enhanceSearchUI();renderRecords()} if(tab==='drivers')renderDrivers(); if(tab==='admins')renderAdmins()}
function updateDashboard(){const r=getRecords(), d=getDrivers(); if($('statToday'))$('statToday').textContent=r.filter(x=>x.date===todayKey()).length; if($('statNeedCheck'))$('statNeedCheck').textContent=r.filter(x=>!x.ok).length; if($('statUnread'))$('statUnread').textContent=r.filter(x=>x.adminComment&&!x.commentRead).length; if($('statDrivers'))$('statDrivers').textContent=d.length; const done=new Set(r.filter(x=>x.date===todayKey()).map(x=>x.driver||x.name)); const miss=d.filter(x=>!done.has(x.name)).map(x=>x.name); $('missingToday').textContent=miss.length?miss.join('、'):'未点呼者はいません'; renderExpiryAlerts(); drawChart()}
function daysUntil(dateStr){if(!dateStr)return null; const d=new Date(dateStr+'T00:00:00'), t=new Date(); t.setHours(0,0,0,0); return Math.ceil((d-t)/(1000*60*60*24))}
function renderExpiryAlerts(){const box=$('expiryAlerts'); if(!box)return; const rows=[]; getDrivers().forEach(d=>{const lic=daysUntil(d.license), ins=daysUntil(d.inspection); if(lic!==null&&lic<=30)rows.push(`⚠️ ${esc(d.name)}：免許期限まで ${lic}日`); if(ins!==null&&ins<=30)rows.push(`⚠️ ${esc(d.name)}：車検期限まで ${ins}日`)}); box.innerHTML=rows.length?rows.map(x=>`<p>${x}</p>`).join(''):'<p>期限アラートはありません</p>'}
function drawChart(){const c=$('summaryChart'); if(!c)return; const ctx=c.getContext('2d'), r=getRecords(); ctx.clearRect(0,0,c.width,c.height); const vals=[r.filter(x=>x.date===todayKey()).length,r.filter(x=>x.month===monthKey()).length,r.filter(x=>!x.ok).length,r.filter(x=>x.adminComment&&!x.commentRead).length], labs=['今日','今月','要確認','未読']; const max=Math.max(...vals,1); ctx.fillStyle='#071f3d'; ctx.font='16px sans-serif'; labs.forEach((l,i)=>{const h=vals[i]/max*160,x=60+i*120;ctx.fillRect(x,210-h,70,h);ctx.fillText(l,x,235);ctx.fillText(vals[i],x+24,200-h)})}
function enhanceSearchUI(){const tab=$('recordsTab'); if(!tab||$('startDateSearch'))return; const grid=tab.querySelector('.grid.three'); grid.innerHTML=`<div><label>ドライバー名</label><select id="driverSelectSearch"><option value="">全員</option></select></div><div><label>開始日</label><input id="startDateSearch" type="date"></div><div><label>終了日</label><input id="endDateSearch" type="date"></div><div><label>判定</label><select id="statusSearch"><option value="">全部</option><option value="ok">OK</option><option value="need">要確認</option></select></div><div><label>未読コメント</label><select id="commentSearch"><option value="">全部</option><option value="unread">未読のみ</option><option value="has">コメントあり</option></select></div><div><label>フリー検索</label><input id="driverSearch" placeholder="名前・車両・備考"></div>`; ['driverSelectSearch','startDateSearch','endDateSearch','statusSearch','commentSearch','driverSearch'].forEach(id=>{bind(id,'change',renderRecords);bind(id,'input',renderRecords)}); renderDriverOptions()}
function renderDriverOptions(){const s=$('driverSelectSearch'); if(!s)return; const cur=s.value; const names=[...new Set(getDrivers().map(d=>d.name).filter(Boolean))]; s.innerHTML='<option value="">全員</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join(''); s.value=cur}
function filteredRecords(){let r=getRecords(); const driver=$('driverSelectSearch')?.value||'', start=$('startDateSearch')?.value||'', end=$('endDateSearch')?.value||'', status=$('statusSearch')?.value||'', com=$('commentSearch')?.value||'', free=$('driverSearch')?.value.trim()||''; if(driver)r=r.filter(x=>(x.driver||x.name)===driver); if(start)r=r.filter(x=>(x.isoDate||'')>=start); if(end)r=r.filter(x=>(x.isoDate||'')<=end); if(status==='ok')r=r.filter(x=>!!x.ok); if(status==='need')r=r.filter(x=>!x.ok); if(com==='unread')r=r.filter(x=>x.adminComment&&!x.commentRead); if(com==='has')r=r.filter(x=>x.adminComment); if(free)r=r.filter(x=>[x.driver,x.name,x.vehicleNo,x.remarks,x.deliveryNote,x.instruction,x.course,x.adminComment].some(v=>String(v||'').includes(free))); return r}
function renderRecords(){const body=$('recordsBody'); if(!body)return; const r=filteredRecords(); if(!r.length){body.innerHTML='<tr><td colspan="9">履歴はありません</td></tr>';return} body.innerHTML=r.map(x=>{const checks=CHECK_ITEMS.map(([id,l])=>`${x.checks?.[id]?'✅':'❌'}${esc(l)}`).join('<br>'); const gps=x.gps?`<a class="maplink" target="_blank" href="https://www.google.com/maps?q=${x.gps.lat},${x.gps.lng}">地図</a>`:''; const unread=x.adminComment&&!x.commentRead; return `<tr><td class="${x.ok?'status-ok':'status-ng'}">${x.ok?'OK':'要確認'}</td><td>${esc(x.time)}</td><td>${esc(x.type)}<br>${esc(x.course||'')}</td><td>${esc(x.driver||x.name)}</td><td>${esc(x.vehicleNo)}<br>${esc(x.odometer)}</td><td>${checks}<br>ALC:${esc(x.alcoholValue||x.alcohol)}<br>睡眠:${esc(x.sleepHours)}</td><td>${gps}</td><td>${x.photo?`<img class="photo" src="${x.photo}">`:''}</td><td>${esc(x.deliveryNote)}<br>${esc(x.remarks)}<hr>${x.adminComment?`💬 ${unread?'<span class="unread">未読</span>':'<span class="read">既読</span>'}<br>${esc(x.adminComment)}`:'コメントなし'}<br><button class="secondary smallbtn" data-comment-id="${x.id}">コメント</button></td></tr>`}).join('')}
function handleRecordClick(e){const btn=e.target.closest('[data-comment-id]'); if(!btn)return; selectedCommentRecordId=btn.dataset.commentId; const rec=getRecords().find(x=>x.id===selectedCommentRecordId); if(!rec)return; $('commentTarget').textContent=`${rec.driver||rec.name} / ${rec.time}`; $('adminCommentText').value=rec.adminComment||''; $('commentPanel').classList.remove('hidden')}
function closeCommentPanel(){selectedCommentRecordId=null; $('commentPanel')?.classList.add('hidden')}
async function saveAdminComment(){if(!selectedCommentRecordId){alert('コメント対象を選択してください');return} const text=$('adminCommentText').value.trim(); const records=getRecords(); const rec=records.find(x=>x.id===selectedCommentRecordId); if(!rec){alert('対象が見つかりません');return} rec.adminComment=text; rec.commentRead=false; rec.commentUpdatedAt=nowText(); setLocal(LS_RECORDS,records); await cloudSave('record',rec); alert('管理者コメントを保存しました'); closeCommentPanel(); renderRecords(); updateDashboard()}
function renderDriverNotices(){if(!currentUser)return; const box=$('driverNoticeBox'), list=$('driverNoticeList'); if(!box||!list)return; const notices=getRecords().filter(x=>(x.driver||x.name)===currentUser&&x.adminComment&&!x.commentRead); if(!notices.length){box.classList.add('hidden'); list.innerHTML=''; return} box.classList.remove('hidden'); list.innerHTML=notices.map(x=>`<div class="notice-item"><p><b>${esc(x.time)}</b></p><p>${esc(x.adminComment)}</p><button class="success smallbtn" data-read-comment-id="${x.id}">確認しました</button></div>`).join('')}
async function handleNoticeClick(e){const btn=e.target.closest('[data-read-comment-id]'); if(!btn)return; const records=getRecords(); const rec=records.find(x=>x.id===btn.dataset.readCommentId); if(!rec)return; rec.commentRead=true; rec.commentReadAt=nowText(); setLocal(LS_RECORDS,records); await cloudSave('record',rec); renderDriverNotices()}
async function addDriver(){const name=$('newDriverName').value.trim(); if(!name){alert('ドライバー名を入力してください');return} const d={id:String(Date.now()),name,tel:$('newDriverTel').value.trim(),license:$('newDriverLicense').value,vehicle:$('newDriverVehicle').value.trim(),inspection:$('newDriverInspection').value,memo:$('newDriverMemo').value.trim(),created:nowText(),createdAt:nowText()}; const a=getDrivers().filter(x=>x.id!==d.id); a.unshift(d); setLocal(LS_DRIVERS,a); await cloudSave('driver',d); ['newDriverName','newDriverTel','newDriverLicense','newDriverVehicle','newDriverInspection','newDriverMemo'].forEach(id=>{if($(id))$(id).value=''}); renderDrivers(); renderDriverOptions(); updateDashboard()}
function renderDrivers(){const body=$('driversBody'); if(!body)return; const d=getDrivers(); if(!d.length){body.innerHTML='<tr><td colspan="8">登録ドライバーはありません</td></tr>';return} body.innerHTML=d.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${esc(x.tel)}</td><td>${esc(x.license)}</td><td>${esc(x.vehicle)}</td><td>${esc(x.inspection||'')}</td><td>${esc(x.memo)}</td><td>${esc(x.created)}</td><td><button class="danger smallbtn" data-delete-driver="${i}">削除</button></td></tr>`).join('')}
async function deleteDriver(i){if(!confirm('このドライバーを削除しますか？'))return; const a=getDrivers(); const d=a[i]; a.splice(i,1); setLocal(LS_DRIVERS,a); if(d?.id)await cloudDelete('driver',d.id); renderDrivers();updateDashboard()}
async function addAdmin(){const name=$('newAdminId').value.trim(), pass=$('newAdminPass').value.trim(); if(!name||!pass){alert('管理者IDとパスワードを入力してください');return} const admin={id:name,name,pass,created:nowText(),createdAt:nowText()}; const a=getAdmins().filter(x=>x.name!==name); a.push(admin); setLocal(LS_ADMINS,a); await cloudSave('admin',admin); $('newAdminId').value='';$('newAdminPass').value=''; renderAdmins()}
function renderAdmins(){const body=$('adminsBody'); if(!body)return; const a=[{id:'admin',name:'admin',created:'初期管理者'},...getAdmins()]; body.innerHTML=a.map((x,i)=>`<tr><td>${esc(x.name)}</td><td>${esc(x.created)}</td><td>${x.id==='admin'?'削除不可':`<button class="danger smallbtn" data-delete-admin="${i-1}">削除</button>`}</td></tr>`).join('')}
async function deleteAdmin(i){const a=getAdmins(); const admin=a[i]; a.splice(i,1); setLocal(LS_ADMINS,a); if(admin?.id)await cloudDelete('admin',admin.id); renderAdmins()}
function exportCSV(){const rows=[['判定','日時','点呼区分','担当コース','名前','車両番号','メーター','アルコール','睡眠','コメント','既読','GPS','備考']]; filteredRecords().forEach(x=>rows.push([x.ok?'OK':'要確認',x.time,x.type,x.course||'',x.driver||x.name,x.vehicleNo,x.odometer,x.alcoholValue||x.alcohol,x.sleepHours,x.adminComment||'',x.commentRead?'既読':'未読',x.gps?`${x.gps.lat},${x.gps.lng}`:'',`${x.deliveryNote||''} ${x.remarks||''}`])); const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n'); const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='belle-house-tenko-search-result.csv'; a.click()}
function backupData(){const data={records:getRecords(),drivers:getDrivers(),admins:getAdmins(),created:nowText(),version:APP_VERSION}; const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='belle-house-tenko-backup.json'; a.click()}
function restoreData(e){const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{try{const data=JSON.parse(r.result); if(data.records)setLocal(LS_RECORDS,data.records); if(data.drivers)setLocal(LS_DRIVERS,data.drivers); if(data.admins)setLocal(LS_ADMINS,data.admins); alert('バックアップを読み込みました'); location.reload()}catch{alert('読み込みに失敗しました')}}; r.readAsText(f)}
async function clearRecords(){if(!confirm('点呼履歴をすべて削除しますか？'))return; localStorage.removeItem(LS_RECORDS); if(window.BELLE_CLOUD?.enabled&&window.BELLE_CLOUD.clearRecords)try{await window.BELLE_CLOUD.clearRecords()}catch(e){console.error(e)} updateDashboard();renderRecords()}
setInterval(()=>{if(!cloudStarted)startCloudSync();updateSyncStatus()},3000);
document.addEventListener('DOMContentLoaded',init);
})();
