(function(){'use strict';
const ADMIN_ID='admin',ADMIN_PASS='1234',LS_RECORDS='belle_house_tenko_v3_final_records',LS_DRIVERS='belle_house_tenko_v3_final_drivers';
let currentUser='',gpsData=null;
const CHECK_ITEMS=[['alcDevice','アルコール検知器を使用した'],['alcNone','酒気帯びなし'],['healthGood','疾病・疲労・睡眠不足なし'],['sleepOk','睡眠不足なし'],['licenseOk','運転免許証を携帯・有効確認'],['dailyInspection','日常点検を実施'],['vehicleOk','車両に異常なし'],['tireOk','タイヤ・灯火・ブレーキ確認'],['cargoOk','積荷・荷崩れ防止確認'],['overloadOk','過積載なし'],['restOk','休憩・拘束時間に無理なし'],['instructionOk','運行上の注意事項を確認']];
const $=id=>document.getElementById(id),nowText=()=>new Date().toLocaleString('ja-JP',{hour12:false}),todayKey=()=>new Date().toLocaleDateString('ja-JP'),isoDate=()=>new Date().toISOString().slice(0,10),monthKey=()=>new Date().toISOString().slice(0,7);
const getRecords=()=>JSON.parse(localStorage.getItem(LS_RECORDS)||'[]'),setRecords=v=>localStorage.setItem(LS_RECORDS,JSON.stringify(v)),getDrivers=()=>JSON.parse(localStorage.getItem(LS_DRIVERS)||'[]'),setDrivers=v=>localStorage.setItem(LS_DRIVERS,JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function init(){renderCheckList();renderSettingsList();bindEvents();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
function bindEvents(){$('loginBtn').onclick=login;$('gpsBtn').onclick=getGPS;$('submitRollcallBtn').onclick=submitRollcall;$('driverLogoutBtn').onclick=logout;$('adminLogoutBtn').onclick=logout;$('exportCsvBtn').onclick=exportCSV;$('clearRecordsBtn').onclick=clearRecords;$('addDriverBtn').onclick=addDriver;$('recordFilter').onchange=renderRecords;$('driverSearch').oninput=renderRecords;$('dateSearch').onchange=renderRecords;document.querySelectorAll('.admin-nav button[data-tab]').forEach(b=>b.onclick=()=>showAdminTab(b.dataset.tab));$('driversBody').onclick=e=>{if(e.target.dataset.deleteDriver!==undefined)deleteDriver(Number(e.target.dataset.deleteDriver));};$('photoInput').onchange=previewPhoto;}
function renderCheckList(){$('checkList').innerHTML=CHECK_ITEMS.map(([id,l])=>`<div class="check"><label><input type="checkbox" id="${id}">${l}</label></div>`).join('');}
function renderSettingsList(){$('settingsList').innerHTML=CHECK_ITEMS.map(([,l])=>`<li>${esc(l)}</li>`).join('');}
function login(){const type=$('loginType').value,name=$('loginName').value.trim(),pass=$('loginPassword').value.trim();if(!name||!pass){alert('名前とパスワードを入力してください');return;}if(type==='admin'){if(name===ADMIN_ID&&pass===ADMIN_PASS){$('loginView').classList.add('hidden');$('adminView').classList.remove('hidden');showAdminTab('dashboard');}else alert('管理者IDまたはパスワードが違います');return;}currentUser=name;$('currentDriver').textContent=`${name} さん`;const d=getDrivers().find(x=>x.name===name);if(d&&d.vehicle)$('vehicleNo').value=d.vehicle;$('loginView').classList.add('hidden');$('driverView').classList.remove('hidden');}
function logout(){location.reload();}
function getGPS(){if(!navigator.geolocation){alert('GPS非対応です');return;}$('gpsText').value='取得中...';navigator.geolocation.getCurrentPosition(p=>{gpsData={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,time:nowText()};$('gpsText').value=`緯度:${gpsData.lat.toFixed(6)} 経度:${gpsData.lng.toFixed(6)} 精度:${Math.round(gpsData.accuracy)}m`;},()=>{gpsData=null;$('gpsText').value='取得失敗';alert('GPS取得に失敗しました。位置情報を許可してください。');},{enableHighAccuracy:true,timeout:10000,maximumAge:0});}
function previewPhoto(){const f=$('photoInput').files[0];if(!f){$('photoPreview').classList.add('hidden');return;}const r=new FileReader();r.onload=()=>{$('photoPreview').src=r.result;$('photoPreview').classList.remove('hidden');};r.readAsDataURL(f);}
function submitRollcall(){const checks={};CHECK_ITEMS.forEach(([id])=>checks[id]=$(id).checked);const allOk=CHECK_ITEMS.every(([id])=>checks[id]);if(!allOk&&!confirm('未チェック項目があります。要確認として送信しますか？'))return;const save=photo=>{const rec={id:String(Date.now()),ok:allOk,time:nowText(),date:todayKey(),isoDate:isoDate(),month:monthKey(),driver:currentUser,type:$('rollcallType').value,method:$('rollcallMethod').value,vehicleNo:$('vehicleNo').value.trim(),odometer:$('odometer').value.trim(),alcoholValue:$('alcoholValue').value.trim(),sleepHours:$('sleepHours').value.trim(),instruction:$('instruction').value.trim(),deliveryNote:$('deliveryNote').value.trim(),checks,gps:gpsData,photo:photo||'',remarks:$('remarks').value.trim()};const arr=getRecords();arr.unshift(rec);setRecords(arr);alert('点呼を送信しました');resetDriverForm();};const f=$('photoInput').files[0];if(f){const r=new FileReader();r.onload=()=>save(r.result);r.readAsDataURL(f);}else save('');}
function resetDriverForm(){['odometer','alcoholValue','sleepHours','instruction','deliveryNote','remarks','gpsText','photoInput'].forEach(id=>$(id).value='');CHECK_ITEMS.forEach(([id])=>$(id).checked=false);$('photoPreview').classList.add('hidden');gpsData=null;}
function showAdminTab(t){document.querySelectorAll('.admin-tab').forEach(e=>e.classList.add('hidden'));$(`${t}Tab`).classList.remove('hidden');if(t==='dashboard')updateDashboard();if(t==='records')renderRecords();if(t==='drivers')renderDrivers();}
function updateDashboard(){const records=getRecords(),drivers=getDrivers();$('statToday').textContent=records.filter(r=>r.date===todayKey()).length;$('statNeedCheck').textContent=records.filter(r=>!r.ok).length;$('statDrivers').textContent=drivers.length;$('statMonth').textContent=records.filter(r=>r.month===monthKey()).length;const todayNames=new Set(records.filter(r=>r.date===todayKey()).map(r=>r.driver));const missing=drivers.filter(d=>!todayNames.has(d.name)).map(d=>d.name);$('missingToday').textContent=missing.length?missing.join('、'):'未点呼者はいません';}
function renderRecords(){const body=$('recordsBody');let records=getRecords();const f=$('recordFilter').value,s=$('driverSearch').value.trim(),d=$('dateSearch').value;if(f==='today')records=records.filter(r=>r.date===todayKey());if(f==='need')records=records.filter(r=>!r.ok);if(f==='month')records=records.filter(r=>r.month===monthKey());if(s)records=records.filter(r=>(r.driver||'').includes(s));if(d)records=records.filter(r=>r.isoDate===d);if(!records.length){body.innerHTML='<tr><td colspan="9">履歴はありません</td></tr>';return;}body.innerHTML=records.map(r=>{const checks=CHECK_ITEMS.map(([id,l])=>`${r.checks?.[id]?'✅':'❌'}${esc(l)}`).join('<br>');const gps=r.gps?`<a class="maplink" target="_blank" href="https://www.google.com/maps?q=${r.gps.lat},${r.gps.lng}">地図</a><br><span class="muted">${Number(r.gps.lat).toFixed(5)}, ${Number(r.gps.lng).toFixed(5)}<br>精度:${Math.round(r.gps.accuracy||0)}m</span>`:'';return `<tr><td class="${r.ok?'status-ok':'status-ng'}">${r.ok?'OK':'要確認'}</td><td>${esc(r.time)}</td><td>${esc(r.type)}<br><span class="muted">${esc(r.method)}</span></td><td>${esc(r.driver)}</td><td>${esc(r.vehicleNo)}<br><span class="muted">${esc(r.odometer)}</span></td><td>${checks}<br>ALC:${esc(r.alcoholValue)}<br>睡眠:${esc(r.sleepHours)}</td><td>${gps}</td><td>${r.photo?`<img class="photo" src="${r.photo}">`:''}</td><td>${esc(r.instruction)}<br>${esc(r.deliveryNote)}<br>${esc(r.remarks)}</td></tr>`;}).join('');}
function addDriver(){const name=$('newDriverName').value.trim();if(!name){alert('ドライバー名を入力してください');return;}const d={id:String(Date.now()),name,tel:$('newDriverTel').value.trim(),license:$('newDriverLicense').value,vehicle:$('newDriverVehicle').value.trim(),memo:$('newDriverMemo').value.trim(),created:nowText()};const arr=getDrivers();arr.unshift(d);setDrivers(arr);['newDriverName','newDriverTel','newDriverLicense','newDriverVehicle','newDriverMemo'].forEach(id=>$(id).value='');renderDrivers();updateDashboard();}
function renderDrivers(){const body=$('driversBody'),drivers=getDrivers();if(!drivers.length){body.innerHTML='<tr><td colspan="7">登録ドライバーはありません</td></tr>';return;}body.innerHTML=drivers.map((d,i)=>`<tr><td>${esc(d.name)}</td><td>${esc(d.tel)}</td><td>${esc(d.license)}</td><td>${esc(d.vehicle)}</td><td>${esc(d.memo)}</td><td>${esc(d.created)}</td><td><button class="danger" data-delete-driver="${i}">削除</button></td></tr>`).join('');}
function deleteDriver(i){if(!confirm('このドライバーを削除しますか？'))return;const arr=getDrivers();arr.splice(i,1);setDrivers(arr);renderDrivers();updateDashboard();}
function exportCSV(){const rows=[['判定','日時','点呼区分','点呼方法','名前','車両番号','メーター','アルコール数値','睡眠時間','緯度','経度','GPS精度m','安全チェック','指示事項','配送注意','備考']];getRecords().forEach(r=>rows.push([r.ok?'OK':'要確認',r.time,r.type,r.method,r.driver,r.vehicleNo||'',r.odometer||'',r.alcoholValue||'',r.sleepHours||'',r.gps?.lat||'',r.gps?.lng||'',r.gps?.accuracy||'',CHECK_ITEMS.map(([id,l])=>`${l}:${r.checks?.[id]?'OK':'NG'}`).join(' / '),r.instruction||'',r.deliveryNote||'',r.remarks||'']));const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\\r\\n');const blob=new Blob(['\\ufeff'+csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='belle-house-tenko-v3-final.csv';a.click();}
function clearRecords(){if(confirm('点呼履歴をすべて削除しますか？')){localStorage.removeItem(LS_RECORDS);renderRecords();updateDashboard();}}
document.addEventListener('DOMContentLoaded',init);
})();